/**
 * LUMINA STUDIO — Unified Architecture Portfolio Engine
 */

// Global App State
let parsedProjects = [];
let slideshowImages = [];
let activeSlideIndex = 0;
let slideshowIntervalId = null;
let pauseTimeoutId = null;
let currentProjectIndex = 0;
let currentImageIndex = 0;

/**
 * 1. Fetch manifest.json generated by GitHub Actions
 */
async function loadPortfolioData() {
  try {
    const response = await fetch('manifest.json', { cache: 'no-store' });
    if (!response.ok) throw new Error(`HTTP ${response.status}`);
    const manifest = await response.json();

    slideshowImages = manifest.slideshow || [];
    parseProjects(manifest.projects || []);
  } catch (err) {
    console.warn("Could not load manifest.json (or testing locally without server).", err);
  }

  // Initialize all UI sections
  initBackgroundSlideshow();
  renderProjectsGrid();
  setupProjectDropdown();
}

/**
 * 2. Parse Project Folders
 * - Sorts naturally (e.g. 01_, 02_, 10_)
 * - Strips everything before and including the first '_' for the display name
 * - Detects image starting with 'Main' (case-insensitive) for the card preview link
 */
function parseProjects(rawProjects) {
  const sorted = [...rawProjects].sort((a, b) =>
    a.folderName.localeCompare(b.folderName, undefined, { numeric: true, sensitivity: 'base' })
  );

  parsedProjects = sorted.map((folder) => {
    const underscoreIndex = folder.folderName.indexOf('_');
    const projectName = underscoreIndex !== -1 
      ? folder.folderName.substring(underscoreIndex + 1).trim() 
      : folder.folderName;

    const mainImgObj = folder.images.find(img => /^main/i.test(img.fileName)) || folder.images[0];

    return {
      folderName: folder.folderName,
      projectName: projectName,
      mainImage: mainImgObj,
      allImages: folder.images
    };
  });

  const countTag = document.getElementById('folder-count-tag');
  const navBadge = document.getElementById('nav-project-count');
  if (countTag) countTag.textContent = `${parsedProjects.length} Projects`;
  if (navBadge) navBadge.textContent = parsedProjects.length;
}

/**
 * Ultra-Smooth Slideshow Transition Engine
 */

let isAnimating = false;

function initBackgroundSlideshow() {
  const wrapper = document.getElementById('slideshow-wrapper');
  if (!wrapper) return;
  wrapper.innerHTML = '';

  if (!slideshowImages || slideshowImages.length === 0) return;

  slideshowImages.forEach((imgUrl, idx) => {
    const slide = document.createElement('div');
    slide.className = `hero-slide ${idx === 0 ? 'active' : ''}`;
    slide.id = `slide-${idx}`;

    const img = document.createElement('img');
    img.src = imgUrl;
    img.alt = '';
    // Preload first three slides for instantaneous stutter-free playback
    img.loading = idx < 3 ? 'eager' : 'lazy';

    img.onerror = () => {
      console.warn(`Failed to load: ${imgUrl}`);
      img.src = defaultSlideshow[idx % defaultSlideshow.length];
    };

    slide.appendChild(img);
    wrapper.appendChild(slide);
  });

  activeSlideIndex = 0;
  startAutoplay();

  // Navigation Arrows (5s pause on manual interaction)
  const prevBtn = document.getElementById('slide-prev-btn');
  const nextBtn = document.getElementById('slide-next-btn');

  if (prevBtn) {
    prevBtn.onclick = (e) => {
      e.stopPropagation();
      prevSlide();
      triggerManualWait();
    };
  }

  if (nextBtn) {
    nextBtn.onclick = (e) => {
      e.stopPropagation();
      nextSlide();
      triggerManualWait();
    };
  }
}

function showSlide(nextIndex, direction = 'next') {
  const slides = document.querySelectorAll('.hero-slide');
  if (slides.length <= 1) return;

  const currentSlide = slides[activeSlideIndex];
  const targetIndex = (nextIndex + slides.length) % slides.length;
  const nextSlideEl = slides[targetIndex];

  if (activeSlideIndex === targetIndex) return;

  // Clean all previous animation states across the deck
  slides.forEach((s) => {
    if (s !== currentSlide && s !== nextSlideEl) {
      s.className = 'hero-slide';
    }
  });

  if (direction === 'next') {
    // 1. Prepare target offscreen to the right without transitions
    nextSlideEl.style.transition = 'none';
    nextSlideEl.className = 'hero-slide enter-from-right';
    void nextSlideEl.offsetHeight; // Force browser layout pass

    // 2. Animate both simultaneously on next frame
    requestAnimationFrame(() => {
      nextSlideEl.style.transition = '';
      currentSlide.className = 'hero-slide exit-left';
      nextSlideEl.className = 'hero-slide active';
    });
  } else {
    // 1. Prepare target offscreen to the left
    nextSlideEl.style.transition = 'none';
    nextSlideEl.className = 'hero-slide enter-from-left';
    void nextSlideEl.offsetHeight;

    // 2. Animate backwards seamlessly
    requestAnimationFrame(() => {
      nextSlideEl.style.transition = '';
      currentSlide.className = 'hero-slide exit-right';
      nextSlideEl.className = 'hero-slide active';
    });
  }

  activeSlideIndex = targetIndex;
}

function nextSlide() {
  showSlide(activeSlideIndex + 1, 'next');
}

function prevSlide() {
  showSlide(activeSlideIndex - 1, 'prev');
}

function startAutoplay() {
  clearInterval(slideshowIntervalId);
  // Smooth continuous interval
  slideshowIntervalId = setInterval(() => {
    nextSlide();
  }, 2000);
}

function triggerManualWait() {
  clearInterval(slideshowIntervalId);
  clearTimeout(pauseTimeoutId);

  // Wait 5 seconds after manual interaction before continuing
  pauseTimeoutId = setTimeout(() => {
    nextSlide();
    startAutoplay();
  }, 5000);
}
/**
 * 4. Render All Projects Grid (1 Main Image Link per Project)
 */
function renderProjectsGrid() {
  const grid = document.getElementById('projects-grid');
  if (!grid) return;
  grid.innerHTML = '';

  parsedProjects.forEach((proj, index) => {
    const card = document.createElement('article');
    card.className = 'project-card';
    card.setAttribute('tabindex', '0');

    card.innerHTML = `
      <div class="card-image-wrap">
        <img src="${proj.mainImage.url}" alt="" loading="lazy" />
      </div>
      <div class="card-content">
        <span class="card-project-name">${proj.projectName}</span>
        <i class="ri-arrow-right-line card-arrow-icon"></i>
      </div>
    `;

    card.onclick = () => openProjectDetail(index);
    grid.appendChild(card);
  });
}

/**
 * 5. Split Project Detail Viewer (1/4th vs 3/4th with Navigation Arrows)
 */
function openProjectDetail(projectIndex) {
  currentProjectIndex = projectIndex;
  currentImageIndex = 0;

  updateProjectDropdown();
  renderThumbnails();
  updateStageImage();

  navigateTo('detail');
}

// 1/4th Section: Thumbnails only (Zero text)
function renderThumbnails() {
  const container = document.getElementById('split-thumbnails');
  if (!container) return;
  container.innerHTML = '';

  const project = parsedProjects[currentProjectIndex];
  if (!project) return;

  project.allImages.forEach((img, idx) => {
    const thumbWrap = document.createElement('div');
    thumbWrap.className = `thumb-item ${idx === currentImageIndex ? 'active' : ''}`;
    thumbWrap.dataset.index = idx;

    const imgEl = document.createElement('img');
    imgEl.src = img.url;
    imgEl.alt = '';

    thumbWrap.appendChild(imgEl);

    thumbWrap.onclick = () => {
      currentImageIndex = idx;
      updateActiveThumbnail();
      updateStageImage();
    };

    container.appendChild(thumbWrap);
  });
}

function updateActiveThumbnail() {
  const thumbs = document.querySelectorAll('.thumb-item');
  thumbs.forEach((t, i) => {
    const isActive = i === currentImageIndex;
    t.classList.toggle('active', isActive);
    if (isActive) {
      t.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
    }
  });
}

// 3/4th Section: Large image only (Zero text)
function updateStageImage() {
  const stageImg = document.getElementById('stage-main-image');
  const project = parsedProjects[currentProjectIndex];
  if (!stageImg || !project) return;

  const currentImage = project.allImages[currentImageIndex] || project.mainImage;
  stageImg.style.opacity = '0.2';
  setTimeout(() => {
    stageImg.src = currentImage.url;
    stageImg.style.opacity = '1';
  }, 100);
}

// Navigation arrows on the right 3/4th stage
function nextStageImage() {
  const project = parsedProjects[currentProjectIndex];
  if (!project || project.allImages.length <= 1) return;

  currentImageIndex = (currentImageIndex + 1) % project.allImages.length;
  updateActiveThumbnail();
  updateStageImage();
}

function prevStageImage() {
  const project = parsedProjects[currentProjectIndex];
  if (!project || project.allImages.length <= 1) return;

  currentImageIndex = (currentImageIndex - 1 + project.allImages.length) % project.allImages.length;
  updateActiveThumbnail();
  updateStageImage();
}

// Custom Dropdown: Main image + Project Name
function setupProjectDropdown() {
  const trigger = document.getElementById('dropdown-trigger');
  const panel = document.getElementById('dropdown-panel');
  if (!trigger || !panel) return;

  const wrapper = trigger.closest('.project-dropdown-wrapper');

  trigger.onclick = (e) => {
    e.stopPropagation();
    wrapper.classList.toggle('open');
  };

  window.addEventListener('click', (e) => {
    if (!wrapper.contains(e.target)) wrapper.classList.remove('open');
  });

  panel.innerHTML = '';
  parsedProjects.forEach((proj, idx) => {
    const item = document.createElement('div');
    item.className = 'dropdown-item';
    item.innerHTML = `
      <img src="${proj.mainImage.url}" alt="" />
      <span class="dropdown-item-name">${proj.projectName}</span>
    `;

    item.onclick = () => {
      wrapper.classList.remove('open');
      openProjectDetail(idx);
    };

    panel.appendChild(item);
  });
}

function updateProjectDropdown() {
  const proj = parsedProjects[currentProjectIndex];
  if (!proj) return;

  const thumb = document.getElementById('dropdown-current-thumb');
  const title = document.getElementById('dropdown-current-name');
  if (thumb) thumb.src = proj.mainImage.url;
  if (title) title.textContent = proj.projectName;

  document.querySelectorAll('.dropdown-item').forEach((item, i) => {
    item.classList.toggle('active', i === currentProjectIndex);
  });
}

/**
 * 6. Page Routing & Event Handlers
 */
function navigateTo(viewId) {
  document.querySelectorAll('.page-view').forEach(view => {
    view.classList.remove('active');
  });

  document.querySelectorAll('.nav-btn, .mobile-nav-btn').forEach(btn => {
    btn.classList.toggle('active', btn.dataset.target === viewId);
  });

  const targetView = document.getElementById(`view-${viewId}`);
  if (targetView) {
    targetView.classList.add('active');
  }

  // Toggle class on body so header is completely transparent on Home,
  // and cleanly legible on content pages like Projects, About, Contact
  if (viewId === 'home') {
    document.body.classList.add('on-home');
    startAutoplay();
  } else {
    document.body.classList.remove('on-home');
    clearInterval(slideshowIntervalId);
    clearTimeout(pauseTimeoutId);
  }

  window.scrollTo({ top: 0, behavior: 'smooth' });
}

function initNavigationEvents() {
  document.querySelectorAll('[data-target]').forEach(btn => {
    btn.addEventListener('click', () => {
      const target = btn.dataset.target;
      navigateTo(target);
      const mobileMenu = document.getElementById('mobile-menu');
      if (mobileMenu) mobileMenu.classList.remove('open');
    });
  });

  const brand = document.getElementById('brand-logo');
  if (brand) {
    brand.onclick = () => navigateTo('home');
  }

  const mobileToggle = document.getElementById('mobile-toggle');
  const mobileMenu = document.getElementById('mobile-menu');
  if (mobileToggle && mobileMenu) {
    mobileToggle.onclick = () => mobileMenu.classList.toggle('open');
  }

  const backBtn = document.getElementById('back-to-projects-btn');
  if (backBtn) {
    backBtn.onclick = () => navigateTo('projects');
  }

  const stagePrevBtn = document.getElementById('stage-arrow-prev');
  const stageNextBtn = document.getElementById('stage-arrow-next');

  if (stagePrevBtn) {
    stagePrevBtn.onclick = (e) => {
      e.stopPropagation();
      prevStageImage();
    };
  }

  if (stageNextBtn) {
    stageNextBtn.onclick = (e) => {
      e.stopPropagation();
      nextStageImage();
    };
  }

  window.addEventListener('keydown', (e) => {
    const homeView = document.getElementById('view-home');
    const detailView = document.getElementById('view-detail');

    if (homeView && homeView.classList.contains('active')) {
      if (e.key === 'ArrowLeft') {
        prevSlide();
        triggerManualWait();
      } else if (e.key === 'ArrowRight') {
        nextSlide();
        triggerManualWait();
      }
    } else if (detailView && detailView.classList.contains('active')) {
      if (e.key === 'ArrowLeft') {
        prevStageImage();
      } else if (e.key === 'ArrowRight') {
        nextStageImage();
      }
    }
  });

  const contactForm = document.getElementById('contact-form');
  if (contactForm) {
    contactForm.onsubmit = (e) => {
      e.preventDefault();
      alert('Thank you for reaching out. Lumina Studio will be in touch shortly.');
      contactForm.reset();
    };
  }
}

document.addEventListener('DOMContentLoaded', () => {
  initNavigationEvents();
  loadPortfolioData();
});